[package]
name = "blang_ir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blang_ast = { path = "../blang_ast" }
blang_span = { path = "../blang_span" }
blang_types = { path = "../blang_types" }
rustc-hash.workspace = true
thiserror = "1.0"
